services:
  - type: web
    name: algocompiler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 src.web.app:app
    envVars:
      - key: PYTHONPATH
        value: src
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
